word = input('Type it something : ')
print('The type primitive this variable is : ', type(word))
print('Spaces ?', word.isspace())
print('Is a Number ?', word.isnumeric())
print('Is a Alphabet ?', word.isalpha())
print('Is a Alphanumeric ? ', word.isalnum())
print('Is it Uppercase letter ?', word.isupper())
print('Is it Lowercase letter ?', word.islower())
print('Is it Capital letter ?', word.istitle())